---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-text-mining/resources/d9pwm) course resource._

---

# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).
* Watch out for potential typos as this is a raw, real-life derived dataset.

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [57]:
import pandas as pd

doc = []
with open('dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df.head(10)

0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
5                    .Per 7/06/79 Movement D/O note:\n
6    4, 5/18/78 Patient's thoughts about current su...
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                         3/7/86 SOS-10 Total Score:\n
9             (4/10/71)Score-1Audit C Score Current:\n
dtype: object

In [86]:
# alldf = pd.DataFrame([df]).transpose()
# alldf[0] = alldf[0].str.lower()
# yowza = alldf[0].str.extract(r'(\d{1,2})[/-](\d{1,2})[/-](\d?\d?\d?\d)', expand = True)
# cols = [1,0,2]
# yowza=yowza[cols]
# yowza.rename(columns={1: "day", 0: "month", 2:"year"}, inplace = True)
# yowza.dropna(inplace = True)

# x = alldf.iloc[125:]
# yowza2 = x[0].str.extract(r'(\d{1,2}) (jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* (\d{4})', expand = True)
# yowza2.rename(columns={0: "day", 1: "month", 2:"year"}, inplace = True)
# yowza2.dropna(inplace = True)

# alldf[0] = alldf[0].str.replace('[,.;:]','')
# x2 = alldf.iloc[194:]
# yowza3 = x2[0].str.extract(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* (\d{1,2}) (\d{4})', expand = True)
# cols = [1,0,2]
# yowza3=yowza3[cols]
# yowza3.rename(columns={1: "day", 0: "month", 2:"year"}, inplace = True)
# yowza3.dropna(inplace = True)

# x3 = alldf.iloc[228:]
# yowza4 = x3[0].str.extract(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* (\d{4})', expand = True)
# yowza4.dropna(inplace = True)
# yowza4['x'] = 1
# cols = ['x',0,1]
# yowza4=yowza4[cols]
# yowza4.rename(columns={'x': "day", 0: "month", 1:"year"}, inplace = True)

# x4 = alldf.iloc[343:]
# yowza5 = x4[0].str.extract(r'(\d{0,2})[/-](\d\d\d\d)', expand = True)
# yowza5.dropna(inplace = True)
# yowza5['x'] = 1
# cols = ['x',0,1]
# yowza5=yowza5[cols]
# yowza5.rename(columns={'x': "day", 0: "month", 1:"year"}, inplace = True)

# x5 = alldf.iloc[455:]
# yowza6 = x5[0].str.extract(r'(\d\d\d\d)', expand = True)
# yowza6['x'] = 1
# yowza6['y'] = 1
# cols = ['x','y',0]
# yowza6=yowza6[cols]
# yowza6.rename(columns={'x': "day", 'y': "month", 0:"year"}, inplace = True)

# union = pd.concat([yowza, yowza2, yowza3, yowza4, yowza5, yowza6])
# vals_to_replace = {'jan':1, 
#                    'feb':2, 
#                    'mar':3,
#                    'apr':4,
#                    'may':5,
#                    'jun':6,
#                    'jul':7,
#                    'aug':8,
#                    'sep':9,
#                    'oct':10,
#                    'nov':11,
#                    'dec':12}
# union.replace({'month':vals_to_replace}, inplace = True)
# union['year'] = union['year'].astype(int)
# union['day'] = union['day'].astype(int)
# union['month'] = union['month'].astype(int)
# # import numpy as np
# union.loc[union['year']<=1000, 'adj year'] = (union['year']+1900).astype(int)
# union.loc[union['year']>1000, 'adj year'] = union['year']
# union['datetime'] = pd.to_datetime(union['adj year']*10000+union['month']*100+union['day'],format='%Y%m%d')
# answer = union['datetime'].rank(method='dense').sub(1).astype("int32")
# answer = answer.sort_values(ascending=True)
# final_answer = (pd.Series(answer.index.values, index=answer ))

In [89]:
# xxx = (pd.Series(answer.index.values, index=answer ))
# xxx.head()

datetime
0     9
1    84
2     2
3    53
4    28
dtype: int64

In [91]:
def date_sorter():
    
#     import pandas as pd

#     doc = []
#     with open('dates.txt') as file:
#         for line in file:
#             doc.append(line)

#     df = pd.Series(doc)
    
    alldf = pd.DataFrame([df]).transpose()
    alldf[0] = alldf[0].str.lower()
    yowza = alldf[0].str.extract(r'(\d{1,2})[/-](\d{1,2})[/-](\d?\d?\d?\d)', expand = True)
    cols = [1,0,2]
    yowza=yowza[cols]
    yowza.rename(columns={1: "day", 0: "month", 2:"year"}, inplace = True)
    yowza.dropna(inplace = True)

    x = alldf.iloc[125:]
    yowza2 = x[0].str.extract(r'(\d{1,2}) (jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* (\d{4})', expand = True)
    yowza2.rename(columns={0: "day", 1: "month", 2:"year"}, inplace = True)
    yowza2.dropna(inplace = True)

    alldf[0] = alldf[0].str.replace('[,.;:]','')
    x2 = alldf.iloc[194:]
    yowza3 = x2[0].str.extract(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* (\d{1,2}) (\d{4})', expand = True)
    cols = [1,0,2]
    yowza3=yowza3[cols]
    yowza3.rename(columns={1: "day", 0: "month", 2:"year"}, inplace = True)
    yowza3.dropna(inplace = True)

    x3 = alldf.iloc[228:]
    yowza4 = x3[0].str.extract(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]* (\d{4})', expand = True)
    yowza4.dropna(inplace = True)
    yowza4['x'] = 1
    cols = ['x',0,1]
    yowza4=yowza4[cols]
    yowza4.rename(columns={'x': "day", 0: "month", 1:"year"}, inplace = True)

    x4 = alldf.iloc[343:]
    yowza5 = x4[0].str.extract(r'(\d{0,2})[/-](\d\d\d\d)', expand = True)
    yowza5.dropna(inplace = True)
    yowza5['x'] = 1
    cols = ['x',0,1]
    yowza5=yowza5[cols]
    yowza5.rename(columns={'x': "day", 0: "month", 1:"year"}, inplace = True)

    x5 = alldf.iloc[455:]
    yowza6 = x5[0].str.extract(r'(\d\d\d\d)', expand = True)
    yowza6['x'] = 1
    yowza6['y'] = 1
    cols = ['x','y',0]
    yowza6=yowza6[cols]
    yowza6.rename(columns={'x': "day", 'y': "month", 0:"year"}, inplace = True)

    union = pd.concat([yowza, yowza2, yowza3, yowza4, yowza5, yowza6])
    vals_to_replace = {'jan':1, 
                       'feb':2, 
                       'mar':3,
                       'apr':4,
                       'may':5,
                       'jun':6,
                       'jul':7,
                       'aug':8,
                       'sep':9,
                       'oct':10,
                       'nov':11,
                       'dec':12}
    union.replace({'month':vals_to_replace}, inplace = True)
    union['year'] = union['year'].astype(int)
    union['day'] = union['day'].astype(int)
    union['month'] = union['month'].astype(int)
#     import numpy as np
    union.loc[union['year']<=1000, 'adj year'] = (union['year']+1900).astype(int)
    union.loc[union['year']>1000, 'adj year'] = union['year']
    union['datetime'] = pd.to_datetime(union['adj year']*10000+union['month']*100+union['day'],format='%Y%m%d')
    answer = union['datetime'].rank(method='dense').sub(1).astype("int32")
    answer = answer.sort_values(ascending=True)
    final_answer = (pd.Series(answer.index.values, index=answer ))
    return final_answer
date_sorter()

datetime
0        9
1       84
2        2
3       53
4       28
5      474
6      153
7       13
8      129
9       98
10     111
11     225
12      31
13     171
14     191
15     486
16     335
16     415
17      36
18     405
18     323
19     422
20     375
21     380
22     345
23      57
24     481
25     436
26     104
27     299
      ...
424    220
425    208
425    243
426    139
427    320
428    383
429    244
429    286
429    480
430    431
431    279
432    198
433    381
433    463
434    366
435    439
435    255
436    401
437    475
438    257
439    152
440    235
441    464
442    253
443    427
443    231
444    141
445    186
446    161
447    413
Length: 500, dtype: int64